CREATE    PROCEDURE dbo.spDeleteUser
@Id INT
AS
BEGIN
   BEGIN TRY
    BEGIN TRANSACTION;
    DELETE [User]
    WHERE Id = @Id
    COMMIT;

    SELECT @Id
END TRY
BEGIN CATCH
    ROLLBACK;
    DECLARE @errorMessage NVARCHAR(MAX) = ERROR_MESSAGE();
    THROW 500000, @errorMessage, 1;
END CATCH;
END


